In [41]:
import numpy as np

## Data Type & Attributes

In [42]:
# Numpy's Main datatype is ndarray  #n dimensional
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [43]:
type(a1)

numpy.ndarray

In [44]:
a2 = np.array([[1,2.0,3.3],
      [4,5,6.5]])

a3 = np.array([
  [
    [1,2,3],
    [4,5,6],
    [7,8,9]
  ],
  [
    [10,11,12],
    [13,14,15],
    [16,17,18],
  ]
])

In [45]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [46]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [47]:
a1.shape

(3,)

In [48]:
a2.shape

(2, 3)

In [49]:
a3.shape

(2, 3, 3)

In [50]:
a1

array([1, 2, 3])

In [51]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [52]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [53]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [54]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [55]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [56]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [57]:
# create a dataframe from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [58]:
sample_array = np.array([1,2,3])
sample_array


array([1, 2, 3])

In [59]:
sample_array.dtype

dtype('int64')

In [60]:
ones = np.ones((2,3))

In [61]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [62]:
ones.dtype

dtype('float64')

In [63]:
type(ones)

numpy.ndarray

In [64]:
zeros = np.zeros((2,3))

In [65]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [66]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [67]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[8, 7, 4, 0, 4],
       [0, 2, 7, 6, 8],
       [4, 3, 7, 6, 8]])

In [68]:
random_array.size

15

In [69]:
random_array.shape

(3, 5)

In [70]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.78751932, 0.3588796 , 0.25268928],
       [0.23487396, 0.88635772, 0.14574641],
       [0.14667646, 0.5195003 , 0.71096624],
       [0.34639666, 0.95103514, 0.57922268],
       [0.84358416, 0.17962919, 0.74339363]])

In [71]:
random_array_2.shape

(5, 3)

In [72]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.21626618, 0.01256101, 0.09341518],
       [0.66240583, 0.3142667 , 0.81570064],
       [0.39304953, 0.88564199, 0.96324277],
       [0.37004844, 0.22093141, 0.21803488],
       [0.28034637, 0.32987962, 0.47429193]])