In [39]:
import numpy as np

## Data Type & Attributes

In [40]:
# Numpy's Main datatype is ndarray  #n dimensional
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [9]:
a2 = np.array([[1,2.0,3.3],
      [4,5,6.5]])

a3 = np.array([
  [
    [1,2,3],
    [4,5,6],
    [7,8,9]
  ],
  [
    [10,11,12],
    [13,14,15],
    [16,17,18],
  ]
])

In [10]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [11]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [12]:
a1.shape

(3,)

In [13]:
a2.shape

(2, 3)

In [14]:
a3.shape

(2, 3, 3)

In [15]:
a1

array([1, 2, 3])

In [16]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [17]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [18]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [19]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [20]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [21]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [22]:
# create a dataframe from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [23]:
sample_array = np.array([1,2,3])
sample_array


array([1, 2, 3])

In [24]:
sample_array.dtype

dtype('int64')

In [25]:
ones = np.ones((2,3))

In [26]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
ones.dtype

dtype('float64')

In [28]:
type(ones)

numpy.ndarray

In [29]:
zeros = np.zeros((2,3))

In [30]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [32]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[0, 9, 9, 4, 1],
       [9, 7, 2, 3, 5],
       [9, 2, 0, 9, 4]])

In [33]:
random_array.size

15

In [34]:
random_array.shape

(3, 5)

In [35]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.47815781, 0.66648339, 0.55782426],
       [0.10302779, 0.745735  , 0.24813395],
       [0.29074849, 0.69708643, 0.95790361],
       [0.50366418, 0.02817856, 0.27222925],
       [0.61475152, 0.06120744, 0.04653811]])

In [36]:
random_array_2.shape

(5, 3)

In [37]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.47608393, 0.79548498, 0.39428229],
       [0.61219119, 0.82756778, 0.39946085],
       [0.87585302, 0.97441254, 0.13144916],
       [0.8050772 , 0.60346593, 0.42910376],
       [0.73593941, 0.0474208 , 0.55244622]])

In [57]:
# Pseudo-random numbers
# np.random.seed(seed=9999)
random_array_4 = np.random.randint(10,size=(5,3))
random_array_4

array([[6, 1, 6],
       [5, 5, 9],
       [6, 8, 0],
       [8, 1, 5],
       [3, 1, 0]])

In [60]:
random_array_4.shape

(5, 3)

In [62]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing arrays and matrices

In [63]:
# find unique number
np.unique(random_array_4)

array([0, 1, 3, 5, 6, 8, 9])

In [64]:
a1

array([1, 2, 3])

In [65]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [66]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])